print("##############################")
print("#                            #")
print("#  Muhammad Azri Rahman      #")
print("#      2410817110016         #")
print("#                            #")
print("##############################")