print("Input")
nama = input('Masukan Nama                          : ')
nim = input('Masukan NIM        : ')
kelas = input('Masukan Kelas Paralel: ')
TempatLahir = input('Masukan Tempat/Tanggal Lahir   : ')
alamat = input("Masukan Alamat: ")
hobby = input("Masukan Hobby: ")
noHP = input("Masukan No. HP: ")

print("Output")
print("Nama                 : ",nama)
print("NIM                  : ",nim)
print("Kelas Paralel        : ",kelas)
print("Tempat/Tanggal Lahir : ",TempatLahir)
print("Alamat               : ",alamat)
print("Hobby                : ",hobby)
print("No. HP               : ",noHP)